apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.26.0  # Update to a more recent version
  - role: worker
    image: kindest/node:v1.26.0
  - role: worker
    image: kindest/node:v1.26.0
  - role: worker
    image: kindest/node:v1.26.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
