apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: nginx
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-app
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        protocol: TCP
